# https://circleci.com/docs/2.0/
version: 2
jobs:
  build-and-pack:
    macos:
      xcode: "8.3.3"
    working_directory: ~/mandelbulber2/
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            brew update
            brew install llvm qt5 gsl lzo jpeg libpng libtiff libsndfile tree p7zip wget
      - run:
          name: Build
          command: |
            export QTDIR="/usr/local/opt/qt5"
            export PATH="$QTDIR/bin:$PATH"
            export LDFLAGS="-L$QTDIR/lib $LDFLAGS"
            export CPPFLAGS="-I$QTDIR/include $CPPFLAGS"
            sh ~/mandelbulber2/mandelbulber2/mac/build_deploy.sh
      - run:
          name: Pack
          command: |
            mkdir -p ~/mandelbulber2/build/artifacts/
            cd ~/mandelbulber2/build/ && 7z a artifacts/mandelbulber2-macOS-$CIRCLE_SHA1.zip mandelbulber2.app
            mv ~/mandelbulber2/build/mandelbulber2.dmg ~/mandelbulber2/build/artifacts/mandelbulber2-macOS-$CIRCLE_SHA1.dmg
            cd ~/mandelbulber2/build/ && tree .
      - store_artifacts:
          path: ~/mandelbulber2/build/artifacts/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-pack



